# Generated by Django 6.0 on 2025-12-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Campus", "Campus"),
                            ("Events", "Events"),
                            ("Tech", "Tech"),
                            ("Academics", "Academics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="articles/")),
                ("author", models.CharField(default="Admin", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
